<<<<<<< HEAD
=======
[build]


# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
>>>>>>> parent of 6f7ac7f (abc)
[build]

  command = "gatsby develop"
  publish = "public"